from distutils.core import setup

setup(
    name='pyfa-ng',
    version='.1',
    packages=['eos', 'eos.fit', 'eos.fit.holder', 'eos.fit.holder.item', 'eos.fit.holder.mixin',
              'eos.fit.holder.mixin.holder', 'eos.fit.holder.container', 'eos.fit.stat_tracker',
              'eos.fit.stat_tracker.register', 'eos.fit.stat_tracker.container', 'eos.fit.restriction_tracker',
              'eos.fit.restriction_tracker.register', 'eos.fit.attribute_calculator', 'eos.data',
              'eos.data.cache_object', 'eos.data.data_handler', 'eos.data.cache_handler', 'eos.data.cache_generator',
              'eos.data.cache_generator.modifier_builder', 'eos.data.cache_generator.modifier_builder.modifier_info',
              'eos.data.cache_generator.modifier_builder.expression_tree', 'eos.data.cache_customizer', 'eos.util',
              'eos.const', 'eos.tests', 'eos.tests.fit', 'eos.tests.fit.specials', 'eos.tests.fit.holder_mixin',
              'eos.tests.fit.holder_mixin.tanking', 'eos.tests.fit.holder_mixin.chargeable',
              'eos.tests.fit.holder_mixin.damage_dealer', 'eos.tests.fit.holder_mixin.damage_dealer.bomb',
              'eos.tests.fit.holder_mixin.damage_dealer.drone', 'eos.tests.fit.holder_mixin.damage_dealer.turret',
              'eos.tests.fit.holder_mixin.damage_dealer.missile', 'eos.tests.fit.holder_mixin.damage_dealer.doomsday',
              'eos.tests.fit.holder_mixin.damage_dealer.specials', 'eos.tests.fit.holder_mixin.damage_dealer.smartbomb',
              'eos.tests.fit.holder_mixin.damage_dealer.fighterbomber', 'eos.tests.fit.holder_container',
              'eos.tests.fit.holder_container.direct', 'eos.tests.fit.holder_container.ordered',
              'eos.tests.fit.holder_container.unordered', 'eos.tests.fit.holder_container.module_racks',
              'eos.tests.fit.holder_container.module_charge', 'eos.tests.stat_tracker', 'eos.tests.stat_tracker.slot',
              'eos.tests.stat_tracker.damage', 'eos.tests.stat_tracker.tanking', 'eos.tests.stat_tracker.resource',
              'eos.tests.cache_generator', 'eos.tests.cache_generator.checks', 'eos.tests.cache_generator.cleanup',
              'eos.tests.cache_generator.conversion', 'eos.tests.modifier_builder', 'eos.tests.modifier_builder.etree',
              'eos.tests.modifier_builder.etree.gang', 'eos.tests.modifier_builder.etree.local',
              'eos.tests.modifier_builder.etree.special', 'eos.tests.modifier_builder.etree.erroneous',
              'eos.tests.modifier_builder.modinfo', 'eos.tests.modifier_builder.modinfo.gang',
              'eos.tests.modifier_builder.modinfo.local', 'eos.tests.modifier_builder.modinfo.special',
              'eos.tests.modifier_builder.modinfo.erroneous', 'eos.tests.modifier_builder.special',
              'eos.tests.restriction_tracker', 'eos.tests.restriction_tracker.restrictions',
              'eos.tests.attribute_calculator', 'eos.tests.attribute_calculator.state',
              'eos.tests.attribute_calculator.special', 'eos.tests.attribute_calculator.chaining',
              'eos.tests.attribute_calculator.modifier_domain', 'eos.tests.attribute_calculator.modifier_domain.direct',
              'eos.tests.attribute_calculator.modifier_domain.direct.disabled_links',
              'eos.tests.attribute_calculator.modifier_domain.filtered',
              'eos.tests.attribute_calculator.modifier_operator',
              'eos.tests.attribute_calculator.modifier_operator.mixed',
              'eos.tests.attribute_calculator.modifier_operator.penaltyImmune',
              'eos.tests.attribute_calculator.modifier_filter_type',
              'eos.tests.attribute_calculator.modifier_source_attribute',
              'eos.tests.attribute_calculator.modifier_target_attribute'],
    url='https://github.com/pyfa-org/pyfa-ng',
    license='GPL',
    author='Pyfa Team',
    author_email='',
    description='Fitting tool for EVE Online',
    requires=['kivy', 'sqlalchemy']
)
