from distutils.core import setup

setup(
    name='Pyfa NG',
    version='.1',
    packages=['services.eos', 'services.eos.fit', 'services.eos.fit.holder', 'services.eos.fit.holder.item',
              'services.eos.fit.holder.mixin', 'services.eos.fit.holder.mixin.holder',
              'services.eos.fit.holder.container', 'services.eos.fit.stat_tracker',
              'services.eos.fit.stat_tracker.register', 'services.eos.fit.stat_tracker.container',
              'services.eos.fit.restriction_tracker', 'services.eos.fit.restriction_tracker.register',
              'services.eos.fit.attribute_calculator', 'services.eos.data', 'services.eos.data.cache_object',
              'services.eos.data.data_handler', 'services.eos.data.cache_handler', 'services.eos.data.cache_generator',
              'services.eos.data.cache_generator.modifier_builder',
              'services.eos.data.cache_generator.modifier_builder.modifier_info',
              'services.eos.data.cache_generator.modifier_builder.expression_tree',
              'services.eos.data.cache_customizer', 'services.eos.util', 'services.eos.const', 'services.eos.tests',
              'services.eos.tests.fit', 'services.eos.tests.fit.specials', 'services.eos.tests.fit.holder_mixin',
              'services.eos.tests.fit.holder_mixin.tanking', 'services.eos.tests.fit.holder_mixin.chargeable',
              'services.eos.tests.fit.holder_mixin.damage_dealer',
              'services.eos.tests.fit.holder_mixin.damage_dealer.bomb',
              'services.eos.tests.fit.holder_mixin.damage_dealer.drone',
              'services.eos.tests.fit.holder_mixin.damage_dealer.turret',
              'services.eos.tests.fit.holder_mixin.damage_dealer.missile',
              'services.eos.tests.fit.holder_mixin.damage_dealer.doomsday',
              'services.eos.tests.fit.holder_mixin.damage_dealer.specials',
              'services.eos.tests.fit.holder_mixin.damage_dealer.smartbomb',
              'services.eos.tests.fit.holder_mixin.damage_dealer.fighterbomber',
              'services.eos.tests.fit.holder_container', 'services.eos.tests.fit.holder_container.direct',
              'services.eos.tests.fit.holder_container.ordered', 'services.eos.tests.fit.holder_container.unordered',
              'services.eos.tests.fit.holder_container.module_racks',
              'services.eos.tests.fit.holder_container.module_charge', 'services.eos.tests.stat_tracker',
              'services.eos.tests.stat_tracker.slot', 'services.eos.tests.stat_tracker.damage',
              'services.eos.tests.stat_tracker.tanking', 'services.eos.tests.stat_tracker.resource',
              'services.eos.tests.cache_generator', 'services.eos.tests.cache_generator.checks',
              'services.eos.tests.cache_generator.cleanup', 'services.eos.tests.cache_generator.conversion',
              'services.eos.tests.modifier_builder', 'services.eos.tests.modifier_builder.etree',
              'services.eos.tests.modifier_builder.etree.gang', 'services.eos.tests.modifier_builder.etree.local',
              'services.eos.tests.modifier_builder.etree.special',
              'services.eos.tests.modifier_builder.etree.erroneous', 'services.eos.tests.modifier_builder.modinfo',
              'services.eos.tests.modifier_builder.modinfo.gang', 'services.eos.tests.modifier_builder.modinfo.local',
              'services.eos.tests.modifier_builder.modinfo.special',
              'services.eos.tests.modifier_builder.modinfo.erroneous', 'services.eos.tests.modifier_builder.special',
              'services.eos.tests.restriction_tracker', 'services.eos.tests.restriction_tracker.restrictions',
              'services.eos.tests.attribute_calculator', 'services.eos.tests.attribute_calculator.state',
              'services.eos.tests.attribute_calculator.special', 'services.eos.tests.attribute_calculator.chaining',
              'services.eos.tests.attribute_calculator.modifier_domain',
              'services.eos.tests.attribute_calculator.modifier_domain.direct',
              'services.eos.tests.attribute_calculator.modifier_domain.direct.disabled_links',
              'services.eos.tests.attribute_calculator.modifier_domain.filtered',
              'services.eos.tests.attribute_calculator.modifier_operator',
              'services.eos.tests.attribute_calculator.modifier_operator.mixed',
              'services.eos.tests.attribute_calculator.modifier_operator.penaltyImmune',
              'services.eos.tests.attribute_calculator.modifier_filter_type',
              'services.eos.tests.attribute_calculator.modifier_source_attribute',
              'services.eos.tests.attribute_calculator.modifier_target_attribute'],
    url='https://github.com/pyfa-org/pyfa-ng',
    license='GPL',
    author='Pyfa Team',
    author_email='',
    description='Fitting tool for EVE Online', requires=['kivy']
)
