<LeftColumn>:
    BoxLayout:
        orientation: 'vertical'
        padding: 20

        Accordion:
            orientation: 'vertical'

            AccordionItem:
                title: 'Market'
                collapse: False

                Label:
                    text: 'Show market here'

            AccordionItem:
                title: 'Ships'

                Label:
                    text: 'Show ship market here'