#:include kv/leftColumnMarket.kv

<LeftColumn>:
    BoxLayout:
        orientation: 'vertical'
        padding: 0

        TabbedPanel:
            size_hint: 1, 1
            pos_hint: {'center_x': .5, 'center_y': .5}
            do_default_tab: False

            TabbedPanelItem:
                text: 'Market'
                LeftColumnMarket:
            TabbedPanelItem:
                text: 'Ships'
                Label:
                    text: 'Show ship market here'
